// 自动生成 by core/quickchat.js —— 请勿手改;游戏更新后重跑 node core/quickchat.js 并重编 VPK
// 桥离线时的快捷语音模板兜底语料(双语,来自本地真实文件)。
// 指纹以全局变量暴露,客户端 syncQuickChat 握手用;旧兑底文件无此变量 → 客户端按指纹缺失路径处理
LCT_QUICKCHAT_FALLBACK_FINGERPRINT = "fnv1a-f9ec2bc3";
LCT_QUICKCHAT_FALLBACK_TEMPLATES = [
 "攻击分路",
 "Attacking Lane",
 "攻击 1 级",
 "Attacking T1",
 "攻击 2 级",
 "Attacking T2",
 "防守基地",
 "Defending Base",
 "防守分路",
 "Defending Lane",
 "防守 1 级",
 "Defending T1",
 "None",
 "推进滑索",
 "Pushing Zipline",
 "我可以治疗你",
 "I can heal you",
 "攻击这个英雄",
 "Attack this hero",
 "别管这个英雄",
 "Ignore this hero",
 "帮忙护送灵瓮",
 "Help with Urn",
 "帮我护送灵瓮",
 "Help me deliver the urn",
 "灵瓮在这里",
 "Urn Here",
 "灵瓮在这里",
 "Spirit Urn is here",
 "攻击{s:hero_name}",
 "Attack {s:hero_name}",
 "马上回来",
 "Be Right Back",
 "小心",
 "Careful",
 "防守分路",
 "Defend Lane",
 "撤退",
 "Get Back",
 "上啊",
 "Go",
 "上了",
 "Going In",
 "前去带线",
 "Going to Rat",
 "比赛很精彩",
 "Good Game",
 "干得漂亮",
 "Good Job",
 "干得漂亮",
 "Good Job",
 "往基地走了",
 "Headed To Base",
 "{s:hero_name}往百老汇走了",
 "{s:hero_name} Headed Broadway",
 "{s:hero_name}往格林威治走了",
 "{s:hero_name} Headed Greenwich",
 "{s:hero_name}往格林威治走了",
 "{s:hero_name} Headed Greenwich",
 "{s:hero_name}往约克走了",
 "{s:hero_name} Headed York",
 "帮助",
 "Help",
 "等等/等一下",
 "Wait/Hold Up",
 "我回来了",
 "I'm Back",
 "看这里",
 "Look here",
 "No",
 "好的",
 "Okay",
 "来了",
 "On my Way",
 "Taunt {s:hero_name}",
 "Praise {s:hero_name}",
 "推进分路",
 "Push Lane",
 "复生石",
 "Rejuv",
 "一起行动",
 "Stay Together",
 "眩晕",
 "Stun",
 "Stun {s:hero_name}",
 "打得很漂亮",
 "Well Played",
 "好的",
 "Yes",
 "准备好了吗",
 "Ready",
 "攻击这里",
 "Attack Here",
 "攻击",
 "Attack",
 "桥上增益",
 "Bridge Buff",
 "正在出这个",
 "Buying This",
 "取消",
 "Cancel",
 "步兵",
 "Troopers",
 "有危险",
 "It's Dangerous",
 "防守基地卫士",
 "Defend Base Guardian",
 "防守卫士",
 "Defend Guardian",
 "防守这里",
 "Defend Here",
 "防卫守护神",
 "Defend Patron",
 "防守圣坛",
 "Defend Shrine",
 "防守机甲",
 "Defend Walker",
 "别出这个",
 "Don't Buy This",
 "传送门",
 "Door",
 "危急",
 "Critical",
 "他们在抢我们的野怪",
 "They're stealing our camps",
 "敌人正在拿下复生石",
 "Enemy Taking Rejuvenator",
 "我来包抄",
 "I'll Flank",
 "跟着我",
 "Follow Me",
 "异化商店",
 "Corrupted Shop",
 "去打钱了",
 "Going to farm",
 "前去带线",
 "Going to rat",
 "商店",
 "Shop",
 "前往基地",
 "Going to Base",
 "前往桥上增益",
 "Going to Bridge Buff",
 "前去防守",
 "Going to Defend",
 "前去推线",
 "Going to Push",
 "前往灵瓮",
 "Going to Urn",
 "我有这个",
 "I Have This",
 "往这边来了",
 "Headed This Way",
 "前往这里",
 "Heading Here",
 "马上复活了",
 "Almost Back",
 "倒下了",
 "Dead",
 "忽略商店",
 "Ignore Shop",
 "忽略",
 "Ignore",
 "忽略商店",
 "Ignore Shop",
 "我要走了",
 "I'm leaving",
 "我跟你走",
 "I'm With You",
 "出的好",
 "Good Pick",
 "裂隙正在形成",
 "Rift Emerging",
 "裂隙在这里",
 "Rift Here",
 "百老汇",
 "Broadway",
 "格林威治",
 "Greenwich",
 "紫路",
 "Purple",
 "约克",
 "York",
 "离开区域",
 "Leaving Area",
 "到这去",
 "Let's Go Here",
 "我们走这边",
 "Let's go this way",
 "藏在这里",
 "Hide Here",
 "拿下复生石",
 "Take the Rejuvenator",
 "魂魄袋",
 "Soul Bag",
 "在这碰头吧",
 "Meet Here",
 "中区头目在这里",
 "Mid Boss is Here",
 "敌人消失",
 "Missing",
 "百老汇敌人失踪",
 "Missing Broadway",
 "格林威治敌人失踪",
 "Missing Greenwich",
 "敌人消失",
 "Missing",
 "格林威治敌人失踪",
 "Missing Greenwich",
 "约克敌人失踪",
 "Missing York",
 "掩护我",
 "Cover Me",
 "计划",
 "Plan",
 "算了",
 "Never mind",
 "未就绪",
 "Not Ready",
 "不要推进",
 "Don't Push",
 "守护神受到攻击",
 "Patron Under Attack",
 "压制",
 "Press",
 "推进基地卫士",
 "Push Base Guardian",
 "推进卫士",
 "Push Guardian",
 "推进守护神",
 "Push Patron",
 "推进圣坛",
 "Push Shrine",
 "推进机甲",
 "Push Walker",
 "Respond 'On My Way'",
 "撤退",
 "Retreat",
 "这有敌人",
 "Enemy Here",
 "已关闭",
 "Closed",
 "迷失者在这里",
 "Sinner's Here",
 "谁来出这个",
 "Someone Buy This",
 "有人来过这里",
 "Someone Was Here",
 "分开推进",
 "Split Push",
 "我们去抢他们的钱",
 "Let's steal their farm",
 "跟紧我",
 "Stick With Me",
 "敌方持有灵瓮",
 "Enemy Has Urn",
 "谢了",
 "Thanks",
 "谢了",
 "Thanks",
 "大招正在冷却",
 "Ultimate Is On Cooldown",
 "大招就绪",
 "Ultimate Ready",
 "帮忙护送灵瓮",
 "Help With Urn",
 "访问商店",
 "Visit Shop",
 "访问商店",
 "Visit Shop",
 "当心",
 "Watch Out",
 "我马上回来",
 "Be right back",
 "小心",
 "Careful",
 "防守分路",
 "Defend Lane",
 "防守百老汇",
 "Defend Broadway",
 "防守格林威治",
 "Defend Greenwich",
 "防守紫路",
 "Defend Purple",
 "防守约克",
 "Defend York",
 "撤退",
 "Get Back",
 "上啊",
 "Go",
 "我要上了",
 "I'm going in",
 "前去带线",
 "Going to Rat",
 "比赛很精彩",
 "Good Game",
 "干得漂亮",
 "Good Job",
 "干得漂亮",
 "Good Job",
 "往基地走了",
 "Headed To Base",
 "前往百老汇",
 "Headed to Broadway",
 "前往格林威治",
 "Headed to Greenwich",
 "往紫路走了",
 "Headed to Purple",
 "前往约克",
 "Headed to York",
 "需要帮助",
 "Need Help",
 "百老汇需要支援",
 "Need Help on Broadway",
 "格林威治需要支援",
 "Need Help on Greenwich",
 "紫路需要帮助",
 "Need Help on Purple",
 "约克需要支援",
 "Need Help on York",
 "等等",
 "Wait",
 "我回来了",
 "I'm Back",
 "看这里",
 "Look here",
 "敌人消失",
 "Missing",
 "No",
 "好的",
 "Okay",
 "来了",
 "On my way",
 "Taunt {s:hero_name}",
 "Praise {s:hero_name}",
 "推进",
 "Push",
 "复生石掉落了",
 "Rejuv's Dropping",
 "跟我来",
 "Come with Me",
 "一起行动",
 "Stay Together",
 "眩晕",
 "Stun",
 "打得很漂亮",
 "Well Played",
 "没问题",
 "Affirmative",
 "准备好了吗",
 "Are you ready",
 "我们攻击这里",
 "Let's attack here",
 "攻击 {s:param_1}",
 "Attack {s:param_1}",
 "{s:param_1}增益在这里",
 "{s:param_1} Buff Here",
 "我在出 {s:param_1}",
 "I'm buying {s:param_1}",
 "我来对付步兵",
 "I'll deal with the troopers",
 "这里很危险",
 "It's dangerous here",
 "防守基地卫士",
 "Defend the Base Guardian",
 "防守百老汇基地卫士",
 "Defend the Broadway Base Guardian",
 "防守格林威治基地卫士",
 "Defend the Greenwich Base Guardian",
 "防守紫路基地卫士",
 "Defend the Purple Base Guardian",
 "防守黄路基地卫士",
 "Defend the York Base Guardian",
 "防守卫士",
 "Defend the Guardian",
 "防守百老汇卫士",
 "Defend the Broadway Guardian",
 "防守格林威治卫士",
 "Defend the Greenwich Guardian",
 "防守紫路卫士",
 "Defend the Purple Guardian",
 "防守黄路卫士",
 "Defend the York Guardian",
 "我们防守这里",
 "Let's defend here",
 "防卫守护神",
 "Defend the Patron",
 "防守圣坛",
 "Defend the Shrine",
 "防守机甲",
 "Defend the Walker",
 "防守百老汇机甲",
 "Defend the Broadway Walker",
 "防守格林威治机甲",
 "Defend the Greenwich Walker",
 "防守紫路机甲",
 "Defend the Purple Walker",
 "防守黄路机甲",
 "Defend the York Walker",
 "别出 {s:param_1}",
 "Don't buy {s:param_1}",
 "传送门在这里",
 "Door's here",
 "马上倒下了",
 "is almost dead",
 "他们在抢我们的野怪",
 "They're stealing our camps",
 "他们在打复生石",
 "They're going for the Rejuvenator",
 "我来包抄他们",
 "I'll flank 'em",
 "准备抓人",
 "Going to Gank",
 "前往经纪商",
 "Going to The Broker",
 "去打钱了",
 "Going to farm",
 "前去带线",
 "Going to rat",
 "前往基地",
 "Going to base",
 "前往{s:param_1}增益",
 "Going to the {s:param_1} Buff",
 "前去防守",
 "Going to defend",
 "前去推线",
 "Going to push",
 "前往灵瓮",
 "Going to the Urn",
 "我方卫士需要支援",
 "Our Guardian Needs Help",
 "百老汇卫士需要支援",
 "Broadway Guardian Needs Help",
 "格林威治卫士需要支援",
 "Greenwich Guardian Needs Help",
 "紫路卫士需要支援",
 "Purple Guardian Needs Help",
 "约克卫士需要支援",
 "York Guardian Needs Help",
 "我有 {s:param_1}",
 "I have {s:param_1}",
 "往分路走了",
 "Headed To Lane",
 "前往这里",
 "Heading here",
 "正在前往分路",
 "Heading to lane",
 "马上复活了",
 "is almost back",
 "倒下了",
 "is dead",
 "别管经纪商",
 "Ignore the Broker",
 "别管 {s:param_1}",
 "Ignore {s:param_1}",
 "忽略商店",
 "Ignore the shop",
 "我要走了",
 "I'm leaving",
 "我跟你走",
 "I'm with you",
 "{s:param_1} 出的真好",
 "{s:param_1} is a good pick",
 "裂隙正在显现",
 "The Rift is Emerging",
 "百老汇出现裂隙",
 "Rift opening on Broadway",
 "格林威治出现裂隙",
 "Rift opening on Greenwich",
 "紫路出现裂隙",
 "The Rift is Emerging on Purple",
 "约克出现裂隙",
 "Rift opening on York",
 "裂隙在这里",
 "Rift Here",
 "裂隙在百老汇",
 "Rift on Broadway",
 "裂隙在格林威治",
 "Rift on Greenwich",
 "裂隙已在紫路降临",
 "The Rift has Arrived on Purple",
 "裂隙在约克",
 "Rift on York",
 "这条路需要支援",
 "This Lane Needs Help",
 "百老汇需要支援",
 "Broadway Needs Help",
 "格林威治需要支援",
 "Greenwich Needs Help",
 "紫路需要支援",
 "Purple Needs Help",
 "约克需要支援",
 "York Needs Help",
 "我要离开这个区域了",
 "I'm leaving the area",
 "我们走这边",
 "Let's go this way",
 "我们在这躲躲",
 "Let's hide here",
 "我们去拿下复生石",
 "Let's go for the Rejuvenator",
 "这里有魂魄袋",
 "Soul bag here",
 "我们在这碰头吧",
 "Let's meet here",
 "中区头目在这里",
 "Mid Boss is Here",
 "百老汇敌人失踪",
 "Missing Broadway",
 "格林威治敌人失踪",
 "Missing Greenwich",
 "不见了",
 "is missing",
 "格林威治敌人失踪",
 "Missing Greenwich",
 "约克敌人失踪",
 "Missing York",
 "掩护我",
 "Cover me",
 "算了",
 "Never mind",
 "我还没准备好团战",
 "I'm not ready for a teamfight",
 "不要太过深入",
 "Don't overextend",
 "他们在打我们的守护神",
 "They're taking our Patron",
 "我们要乘胜追击",
 "We need to press the advantage",
 "推进基地卫士",
 "Push the Base Guardian",
 "推进百老汇基地卫士",
 "Push the Broadway Base Guardian",
 "推进格林威治基地卫士",
 "Push the Greenwich Base Guardian",
 "推进紫路基地卫士",
 "Push the Purple Base Guardian",
 "推进约克基地卫士",
 "Push the York Base Guardian",
 "推进卫士",
 "Push the Guardian",
 "推进百老汇卫士",
 "Push the Broadway Guardian",
 "推进格林威治卫士",
 "Push the Greenwich Guardian",
 "推进紫路卫士",
 "Push the Purple Guardian",
 "推进约克卫士",
 "Push the York Guardian",
 "推进守护神",
 "Push the Patron",
 "推进圣坛",
 "Push the Shrine",
 "推进机甲",
 "Push the Walker",
 "推进百老汇机甲",
 "Push the Broadway Walker",
 "推进格林威治机甲",
 "Push the Greenwich Walker",
 "推进紫路机甲",
 "Push the Purple Walker",
 "推进约克机甲",
 "Push the York Walker",
 "商店已关闭",
 "Shop's closed",
 "迷失者抉择在这里",
 "Sinner's Sacrifice is here",
 "谁来出 {s:param_1}",
 "Someone buy {s:param_1}",
 "有人来过这里",
 "Someone was here",
 "我们分头推线",
 "Let's split push",
 "我们去抢他们的钱",
 "Let's steal their farm",
 "跟紧我",
 "Stick with me",
 "他们拿到灵瓮了",
 "They have the Urn",
 "谢了",
 "Thanks",
 "谢了",
 "Thanks",
 "{s:param_1}的大招正在冷却",
 "{s:param_1}'s Ultimate is on cooldown",
 "我的大招正在冷却",
 "My Ultimate is on cooldown",
 "{s:param_1}的大招好了",
 "{s:param_1}'s Ultimate is ready",
 "我的大招好了",
 "My Ultimate is ready",
 "帮忙护送灵瓮",
 "Help deliver the Urn",
 "访问经纪商",
 "Visit the Broker",
 "访问商店",
 "Visit the shop",
 "当心",
 "Watch out",
 "没问题",
 "No Problem",
 "推进百老汇",
 "Push Broadway",
 "推进格林威治",
 "Push Greenwich",
 "推进紫路",
 "Push Purple",
 "推进约克",
 "Push York",
 "回复给：",
 "Responding to:",
 "{s:param_1}正在冷却",
 "{s:param_1} is on cooldown",
 "{s:param_1}好了",
 "{s:param_1} is ready",
 "没问题",
 "Affirmative",
 "优先目标",
 "Priority target",
 "去打他们的守护神",
 "Let's take their Patron",
 "百老汇需要支援",
 "Broadway Needs Help",
 "小心",
 "Careful",
 "防守",
 "Defend",
 "防守基地",
 "Defend the Base",
 "防守百老汇",
 "Defend Broadway",
 "防守格林威治",
 "Defend Greenwich",
 "防守格林威治",
 "Defend Greenwich",
 "防守约克",
 "Defend York",
 "他们全在这里",
 "They're all here",
 "他们来了很多人",
 "There's a lot of them",
 "他们来了两个人",
 "There's two of them",
 "has {s:param_2}",
 "他们在打中区头目",
 "They're taking mid",
 "我要上了",
 "I'm going in",
 "干得漂亮",
 "Good job",
 "格林威治需要支援",
 "Greenwich Needs Help",
 "前往百老汇",
 "Headed to Broadway",
 "前往格林威治",
 "Headed to Greenwich",
 "前往格林威治",
 "Headed to Greenwich",
 "前往约克",
 "Headed to York",
 "我回来了",
 "I'm Back",
 "灵瓮在此",
 "Spirit Urn is here",
 "不稳定裂隙在这里",
 "Unstable Rift is here",
 "我们去百老汇",
 "Let's go Broadway",
 "我们去格林威治",
 "Let's go Greenwich",
 "我们去格林威治",
 "Let's go Greenwich",
 "我们走这边",
 "Let's go this way",
 "我们去约克",
 "Let's go York",
 "百老汇敌人失踪",
 "Missing Broadway",
 "格林威治敌人失踪",
 "Missing Greenwich",
 "格林威治敌人失踪",
 "Missing Greenwich",
 "约克敌人失踪",
 "Missing York",
 "百老汇需要支援",
 "Need help Broadway",
 "格林威治需要支援",
 "Need help Greenwich",
 "格林威治需要支援",
 "Need help Greenwich",
 "约克需要支援",
 "Need help York",
 "算了",
 "Cancel That",
 "干得不错",
 "Nice work",
 "我马上就到",
 "On my Way",
 "格林威治需要支援",
 "Greenwich Needs Help",
 "我们一起推百老汇",
 "Let's Push Broadway",
 "我们一起推格林威治",
 "Let's Push Greenwich",
 "我们一起推格林威治",
 "Let's Push Greenwich",
 "我们一起推约克",
 "Let's Push York",
 "跟着我",
 "Follow me",
 "Pull back",
 "被发现了",
 "Spotted",
 "在这里，{s:param_2}点生命",
 "is here with {s:param_2} health",
 "一起行动",
 "Stay Together",
 "快点晕人",
 "Stun please",
 "去打他们的核心",
 "Let's take out their core",
 "我们去拿下中区头目",
 "Let's take mid",
 "谢谢",
 "Thank You",
 "敌人",
 "the enemy",
 "他们",
 "They're",
 "他们在打我们的守护神",
 "They're taking our Patron",
 "{s:param_1}好了",
 "{s:param_1} is ready",
 "约克需要支援",
 "York Needs Help"
];
