// 自动生成 by core/game_names.js —— 请勿手改;游戏更新后重跑 node core/game_names.js 并重编 VPK
// 名称保护兜底名单(英文原名 -> 中文译名),桥离线时用;指纹供 btipc07 握手比对,
// 指纹相同 = 游戏侧这份与桥一致 → 一条数据都不用传。
LCT_GAMENAMES_PAIRS_FP = "fnv1a-cde876fa";
LCT_GAMENAMES_PAIRS = {
 "Abrams": "亚伯兰",
 "Active Reload": "高速装填",
 "Aerial Supremacy": "空中霸权",
 "Akimbo": "阿金驳",
 "Alchemical Fire": "炼金之火",
 "Ammo Scavenger": "拾弹能手",
 "Ancient Shield": "远古战盾",
 "Apex Combat": "巅峰之战",
 "Apocalypse": "Apocalypse",
 "Apollo": "阿波罗",
 "Arcane Surge": "秘法涌动",
 "Architect": "Architect",
 "Arctic Blast": "极地冰暴",
 "Armor Piercer": "穿甲弹",
 "Assassin": "Assassin",
 "Baba": "婆婆",
 "Ballista": "Ballista",
 "Ballistic Enchantment": "弹道附魔",
 "Battle Vest": "战斗背心",
 "Bebop": "比波普",
 "Berserker": "狂战士",
 "Billy": "比利",
 "Blood Tribute": "殷红贡礼",
 "Boho": "波米",
 "Bomber": "Bomber",
 "Boundless Spirit": "灵力无边",
 "Bullet Armor": "子弹护甲",
 "Bullet Lifesteal": "子弹回复",
 "Bullet Resilience": "子弹坚甲",
 "Bullet Resist Shredder": "粉碎护甲",
 "Burst Fire": "健步疾射",
 "Cadence": "Cadence",
 "Calico": "卡厉可",
 "Capacitor": "积雷电容",
 "Celeste": "赛凌",
 "Celestial Blessing": "上界福佑",
 "Cheat Death": "幸免于难",
 "Clawdril": "Clawdril",
 "Cloak of Opportunity": "机遇斗篷",
 "Close Quarters": "近身决斗",
 "Cold Front": "冰天雪地",
 "Cold Metal": "Cold Metal",
 "Colossus": "巨人",
 "Compress Cooldown": "冷却压缩",
 "Conjure Missiles": "召唤导弹",
 "Counterspell": "法术反制",
 "Cowboy": "Cowboy",
 "Crippling Headshot": "头弹破防",
 "Crushing Fists": "粉碎重拳",
 "Cultist Sacrifice": "特异供奉",
 "Cursed Relic": "天谴圣物",
 "Deadman Danny": "空骨丹尼",
 "Debuff Reducer": "减益缩短",
 "Decay": "衰变",
 "Demolitions Expert": "Demolitions Expert",
 "Disarming Hex": "缴械魔咒",
 "Dispel Magic": "驱散魔法",
 "Divine Barrier": "神圣屏障",
 "Diviner's Kevlar": "金刚宝衫",
 "Doorman": "门侍",
 "Drifter": "孤猎",
 "Druid": "Druid",
 "Duo": "Duo",
 "Duration Extender": "余威回荡",
 "Dynamo": "奇能",
 "Echo Shard": "回音碎片",
 "Electric Slippers": "霹雳便鞋",
 "Enchanter's Emblem": "附魔师纹章",
 "Endless Magazine": "无尽弹匣",
 "Enduring Speed": "疾速不怠",
 "Enduring Spirit": "元灵常驻",
 "English": "schinese",
 "Escalating Exposure": "伤上加伤",
 "Escalating Resilience": "层层防御",
 "Eternal Gift": "天赐之礼",
 "Ethereal Shift": "身躯虚化",
 "Explosive Demolition": "惊天爆破",
 "Express Shot": "疾速射击",
 "Extended Magazine": "扩容弹匣",
 "Extra Charge": "额外充能",
 "Extra Health": "额外生命",
 "Extra Regen": "加速回复",
 "Extra Spirit": "灵力扩增",
 "Extra Stamina": "耐力补给",
 "Fathom": "海魇",
 "Fleetfoot": "轻盈飞步",
 "Focus Lens": "聚焦透镜",
 "Fortitude": "坚毅之心",
 "Fortuna": "Fortuna",
 "Frenzy": "狂乱",
 "Frostbite Charm": "寒霜护符",
 "Fury Trance": "怒意之潮",
 "Gadget Man": "Gadget Man",
 "Gadgeteer": "Gadgeteer",
 "Generic Person": "无名氏",
 "Glass Cannon": "玻璃大炮",
 "Glass Cannon v2": "玻璃大炮",
 "Glider": "Glider",
 "Golden Goose Egg": "金鹅蛋",
 "Graf": "Graf",
 "Graves": "格瑞墓",
 "Greater Expansion": "强效扩张",
 "Grey Talon": "灰爪",
 "Grit": "刚毅",
 "Guardian Ward": "护卫结界",
 "Gunner": "Gunner",
 "Gunslinger": "Gunslinger",
 "Haunting Scream": "作祟尖叫",
 "Haunting Shot": "灵异子弹",
 "Haze": "岚梦",
 "Headhunter": "猎头",
 "Headshot Booster": "头弹奖励",
 "Healbane": "不治魔咒",
 "Healing Booster": "治疗强化",
 "Healing Nova": "治疗之环",
 "Healing Rite": "治疗仪式",
 "Healing Tempo": "治疗律动",
 "Heroic Aura": "英雄光环",
 "Hex-Sealed Knuckles": "咒印铁拳",
 "Hexafoil Ward": "六叶结界",
 "High-Velocity Rounds": "高速弹",
 "Hijack": "Hijack",
 "Holliday": "哈雷黛",
 "Hollow Point": "空尖弹",
 "Hungering Blade": "渴望之刃",
 "Hunter's Aura": "猎人光环",
 "Improved Spirit": "灵力高涨",
 "Indomitable": "不屈之志",
 "Infernus": "炽焱",
 "Infinite Rounds": "无限弹匣",
 "Infuser": "灵力灌注",
 "Inhibitor": "抑制术",
 "Intensifying Magazine": "火力渐升",
 "Ivy": "青藤",
 "Juggernaut": "破阵之势",
 "Kali": "Kali",
 "Kelvin": "开尔文",
 "Kinetic Dash": "动能冲刺",
 "Knockdown": "天锤压顶",
 "Lady Geist": "盖斯特夫人",
 "Lash": "劳什",
 "Leech": "赤蟥",
 "Lifestrike": "生命打击",
 "Lightning Scroll": "雷鸣卷轴",
 "Long Range": "远击威力",
 "Lucky Shot": "幸运一击",
 "Magic Carpet": "魔毯",
 "Majestic Leap": "升空飞跃",
 "Majestic Leap - Disabled": "升空飞跃已禁用",
 "McGinnis": "麦金妮",
 "Mecha Guy": "Mecha Guy",
 "Melee Charge": "近战蓄力",
 "Melee Lifesteal": "近战疗法",
 "Mercurial Magnum": "水银重弹",
 "Metal Skin": "铜皮铁骨",
 "Mina": "米娜",
 "Mirage": "蜃景",
 "Mo & Krill": "莫克双雄",
 "Monster Rounds": "猎怪弹",
 "Mystic Burst": "秘术爆发",
 "Mystic Conduit": "秘术管道",
 "Mystic Expansion": "秘术扩张",
 "Mystic Regeneration": "秘术愈疗",
 "Mystic Reverb": "秘术余波",
 "Mystic Shot": "秘术射击",
 "Mystic Slow": "秘术缓速",
 "Mystic Vulnerability": "秘术脆弱",
 "Mystical Piano": "神秘钢琴",
 "Nullification Burst": "否决爆发",
 "Nurse Harrow": "亥芮护士",
 "Omnicharge Signet": "跃升之印",
 "Opening Rounds": "先发强袭",
 "Opera": "Opera",
 "Paige": "佩吉",
 "Paradox": "悖论",
 "Patron's Healing": "守护神的治疗",
 "Phalanx": "Phalanx",
 "Phantom Strike": "幻影突袭",
 "Phoenix": "Phoenix",
 "Plated Armor": "铁板重甲",
 "Pocket": "口袋",
 "Point Blank": "近身猛击",
 "Prism Blast": "棱镜冲击",
 "Quicksilver Reload": "魔力装填",
 "Radiant Regeneration": "容光焕发",
 "Rapid Recharge": "火速充能",
 "Rapid Rounds": "快手连发",
 "Rat King": "鼠王",
 "Raven": "渡鸦",
 "Reactive Barrier": "应急屏障",
 "Rebirth": "重生",
 "Rebuttal": "对等还击",
 "Recharging Rush": "能量迸发",
 "Refresher": "刷新环",
 "Rem": "雷姆",
 "Rescue Beam": "营救光束",
 "Restorative Locket": "疗愈护符",
 "Restorative Shot": "疗愈子弹",
 "Return Fire": "回应射击",
 "Revenant": "Revenant",
 "Ricochet": "跳弹射击",
 "Runed Gauntlets": "符文手套",
 "Rusted Barrel": "锈蚀枪管",
 "Rutger": "Rutger",
 "Sapper": "Sapper",
 "Scourge": "敌之灾患",
 "Seraphim Wings": "炽天使之翼",
 "Seven": "柒",
 "Shadow Step": "幽影瞬步",
 "Shadow Strike": "暗影突袭",
 "Shadow Weave": "来去无踪",
 "Sharpshooter": "弹无虚发",
 "Shield Guy": "盾男",
 "Shiv": "希弗",
 "Shrink Ray": "缩小射线",
 "Silence Wave": "沉默之潮",
 "Silencer": "沉默子弹",
 "Silver": "西尔芙",
 "Sinclair": "无双魔术师",
 "Siphon Bullets": "虹吸弹",
 "Sky Monk": "Sky Monk",
 "Skyrunner": "御空行者",
 "Slingshot": "Slingshot",
 "Slowing Bullets": "减速弹",
 "Slowing Hex": "减速魔咒",
 "Solomon": "所罗门",
 "Soul Explosion": "灵魂爆炸",
 "Soul Rebirth": "原地复活",
 "Spade": "Spade",
 "Spellbreaker": "破咒护符",
 "Spellslinger": "施术之手",
 "Spirit Armor": "元灵护甲",
 "Spirit Burn": "元灵燃烧",
 "Spirit Lifesteal": "元灵吸收",
 "Spirit Rend": "元灵撕裂",
 "Spirit Resilience": "元灵护体",
 "Spirit Sap": "元灵衰竭",
 "Spirit Shielding": "元灵防护",
 "Spirit Shredder": "碎灵子弹",
 "Spirit Snatch": "元灵收割",
 "Spirit Strike": "大伤元气",
 "Spiritual Overflow": "元灵漫溢",
 "Split Shot": "裂光射击",
 "Sprint Boots": "疾跑靴",
 "Stalker": "追猎",
 "Stamina Mastery": "跑酷大师",
 "Superior Cooldown": "超速冷却",
 "Superior Duration": "余威久久",
 "Suppressor": "元灵压制",
 "Surge of Power": "灵能涌动",
 "Swan": "天鹅舞伶",
 "Swift Striker": "迅捷突击",
 "Tankbuster": "重装克星",
 "TargetDummy": "假人靶子",
 "Tempest": "Tempest",
 "Tesla Bullets": "特斯拉弹",
 "Test Hero": "测试英雄",
 "The Boss": "Boss",
 "The Doorman": "门侍",
 "Thumper": "Thumper",
 "Timeless Emblem": "永恒纹章",
 "Titanic Magazine": "巨型弹匣",
 "Tokamak": "Tokamak",
 "Torment Pulse": "痛苦脉冲",
 "Toughness": "坚韧",
 "Toxic Bullets": "毒弹",
 "Transcendent Cooldown": "超凡冷却",
 "Trapper": "陷阱师",
 "Trophy Collector": "寻猎季节",
 "Unstable Concoction": "不稳定化合物",
 "Unstoppable": "势不可挡",
 "Vampire": "Vampire",
 "Vampiric Burst": "疗愈爆发",
 "Vandal": "Vandal",
 "Veil Walker": "穿幕行者",
 "Venator": "诛邪者",
 "Victor": "维克多",
 "Vindicta": "薇妲",
 "Violet": "阿紫",
 "Viscous": "魔液",
 "Vortex Web": "雷织漩涡",
 "Vyper": "蝰邪",
 "Warden": "沃督",
 "Warp Stone": "传送石",
 "Weakening Headshot": "头弹弱防",
 "Weapon Shielding": "武器防护",
 "Weighted Shots": "重压射击",
 "Witchmail": "巫师护甲",
 "Wraith": "灵魅",
 "Wrecker": "破坏王",
 "Yamato": "大和",
 "Zealot": "Zealot"
};
